# This workflow will start Docker container and run tests

name: Continuous integration

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Start docker images for tests
      run: |
        docker-compose -f docker-compose.yml --env-file=.env.default up -d
    - name: Run unit tests
      run: |
        docker exec flexchange-api-1 /bin/bash -c "pytest flexchange --cov=flexchange"
