# This workflow will start Docker container and run tests

name: Continuous integration

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: Start docker images for tests
      run: |
        mv .env.default .env
        docker-compose -f docker-compose.yml up -d
    - name: Run unit tests
      run: |
        docker exec flexchange_api_1 /bin/bash -c "pytest flexchange \
                                                  --cache-clear \
                                                  --no-cov-on-fail \
                                                  --cov=flexchange
                                                  --cov-report html:reports/cov-html/flexchange-unit \
                                                  --cov-report xml:reports/cov/flexchange-unit.xml \
                                                  --junitxml=reports/junit/flexchange-unit.xml"
    - name: Collect results of Automated Tests
        if: always()
        run: |
          mkdir reports
          # don't fail if a .xml file is not found, just continue with next command
          docker cp flexchange_api_1:/app/src/reports/.  ./reports/ || true
    - name: Upload results of Automated Tests
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: Test Results
        path: reports/
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2.2.0
      if: always()
      with:
        junit_files: reports/junit/*.xml
        check_run_annotations: all tests, skipped tests
        check_name: "Unit Test Results"
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
