# This workflow will start Docker container and run tests

name: Continuous integration

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0
    - name: Start docker images for tests
      run: |
        mv .env.default .env
        docker-compose -f docker-compose.yml up -d
    - name: Run unit tests
      run: |
        docker exec flexchange_api_1 /bin/bash -c "pytest flexchange \
                                                  --cache-clear \
                                                  --no-cov-on-fail \
                                                  --cov=flexchange \
                                                  --cov-report html:reports/cov-html/flexchange-unit \
                                                  --cov-report xml:reports/cov/flexchange-unit.xml \
                                                  --junitxml=reports/junit/flexchange-unit.xml"
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
